import mongoose from "mongoose";

const generatedReportSchema = new mongoose.Schema(
  {
    // Unique report ID
    reportId: {
      type: String,
      unique: true,
      required: true,
      default: () => `RPT-${Date.now()}`,
    },

    // Report title
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 200,
    },

    // Report type
    reportType: {
      type: String,
      required: true,
      enum: [
        "daily-summary",
        "weekly-summary",
        "monthly-summary",
        "issue-report",
        "performance-report",
        "department-report",
        "custom",
      ],
      default: "daily-summary",
    },

    // Date range for the report
    dateRange: {
      startDate: { type: Date, required: true },
      endDate: { type: Date, required: true },
    },

    // Filters applied
    filters: {
      categories: [String],
      statuses: [String],
      priorities: [String],
      departments: [String],
      areas: [String],
    },

    // Report format
    format: {
      type: String,
      enum: ["pdf", "csv", "excel", "json"],
      default: "pdf",
    },

    // Status
    status: {
      type: String,
      required: true,
      enum: ["generating", "completed", "failed"],
      default: "generating",
    },

    // Generated by
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Report data (stored as JSON)
    reportData: {
      summary: {
        totalIssues: Number,
        resolved: Number,
        pending: Number,
        inProgress: Number,
        avgResolutionTime: String,
      },
      categoryBreakdown: [
        {
          category: String,
          count: Number,
          resolved: Number,
          percentage: Number,
        },
      ],
      priorityBreakdown: [
        {
          priority: String,
          count: Number,
          resolved: Number,
        },
      ],
      statusBreakdown: [
        {
          status: String,
          count: Number,
        },
      ],
      topIssues: [
        {
          issueId: String,
          title: String,
          status: String,
          upvotes: Number,
        },
      ],
      departmentPerformance: [
        {
          department: String,
          assigned: Number,
          resolved: Number,
          avgTime: String,
        },
      ],
      dailyTrends: [
        {
          date: String,
          reported: Number,
          resolved: Number,
        },
      ],
    },

    // File URL (if PDF/CSV generated)
    fileUrl: {
      type: String,
    },

    // File size in bytes
    fileSize: {
      type: Number,
    },

    // Include charts
    includeCharts: {
      type: Boolean,
      default: true,
    },

    // Additional notes
    notes: {
      type: String,
      maxlength: 500,
    },

    // Completed at
    completedAt: Date,

    // Error message if failed
    errorMessage: String,
  },
  {
    timestamps: true,
  }
);

// Indexes
generatedReportSchema.index({ generatedBy: 1, createdAt: -1 });
generatedReportSchema.index({ status: 1 });

export default mongoose.model("GeneratedReport", generatedReportSchema);
